name: centos7-ansible-latest
on:
  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    paths:
      - 'centos7-ansible-latest/**'
  pull_request:
    paths:
      - 'centos7-ansible-latest/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        dockerimage:
          - centos7-ansible
        platforms:
          - linux/amd64
          # #- linux/arm64  # not supported upstream
    steps:
      -
        name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.dockerimage }}-latest
          tags: docker-${{ matrix.dockerimage }}:test
          platforms: ${{ matrix.platforms }}
          load: true
      -
        name: Test
        run: |
          docker run --rm docker-${{ matrix.dockerimage }}:test
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
      -
        name: Build and push to ghcr.io
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.dockerimage }}-latest
          push: true
          tags: ghcr.io/dev-sec/docker-${{ matrix.dockerimage }}:latest
          platforms: ${{ matrix.platforms }}
        if: github.ref == 'refs/heads/master'
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.dockerimage }}-latest
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-${{ matrix.dockerimage }}:latest
          platforms: ${{ matrix.platforms }}
        if: github.ref == 'refs/heads/master'
