name: debian11-ansible-latest
on:
  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    paths:
      - 'debian11-ansible-latest/**'
  pull_request:
    paths:
      - 'debian11-ansible-latest/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerimage:
          - debian11-ansible
        platforms:
          - linux/amd64
          #- linux/arm64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.dockerimage }}-latest
          tags: docker-${{ matrix.dockerimage }}:test
          platforms: ${{ matrix.platforms }}
          load: true
      -
        name: Test
        run: |
          docker run --rm docker-${{ matrix.dockerimage }}:test
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.dockerimage }}-latest
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-${{ matrix.dockerimage }}:latest
          platforms: ${{ matrix.platforms }}
        if: github.ref == 'refs/heads/master'
